"""Hand-authored Northwind question-to-SQL examples for retrieval."""
from __future__ import annotations

EXAMPLE_PAIRS: list[dict[str, str]] = [
    {"id": "simple_customers", "question": "List customers in Germany", "sql": "SELECT customers.customer_id, customers.company_name, customers.city FROM customers WHERE customers.country = 'Germany' LIMIT 100;"},
    {"id": "simple_products", "question": "Show products with low inventory", "sql": "SELECT products.product_id, products.product_name, products.units_in_stock FROM products ORDER BY products.units_in_stock ASC LIMIT 20;"},
    {"id": "simple_orders", "question": "Show recent orders", "sql": "SELECT orders.order_id, orders.customer_id, orders.order_date, orders.freight FROM orders ORDER BY orders.order_date DESC LIMIT 20;"},
    {"id": "simple_suppliers", "question": "List suppliers by country", "sql": "SELECT suppliers.country, COUNT(*) AS supplier_count FROM suppliers GROUP BY suppliers.country ORDER BY supplier_count DESC;"},
    {"id": "join_orders_customers", "question": "Show orders with customer names", "sql": "SELECT orders.order_id, customers.company_name, orders.order_date FROM orders JOIN customers ON orders.customer_id = customers.customer_id ORDER BY orders.order_date DESC LIMIT 50;"},
    {"id": "join_products_categories", "question": "Show products and their categories", "sql": "SELECT products.product_name, categories.category_name FROM products JOIN categories ON products.category_id = categories.category_id LIMIT 100;"},
    {"id": "join_products_suppliers", "question": "Show products with supplier names", "sql": "SELECT products.product_name, suppliers.company_name AS supplier_name FROM products JOIN suppliers ON products.supplier_id = suppliers.supplier_id LIMIT 100;"},
    {"id": "join_orders_shippers", "question": "Average freight by shipper", "sql": "SELECT shippers.company_name AS shipper_name, AVG(orders.freight) AS average_freight FROM orders JOIN shippers ON orders.ship_via = shippers.shipper_id GROUP BY shippers.company_name ORDER BY average_freight DESC;"},
    {"id": "three_customer_revenue", "question": "Top customers by revenue", "sql": "SELECT customers.customer_id, customers.company_name, SUM(order_details.unit_price * order_details.quantity * (1 - order_details.discount)) AS total_revenue FROM customers JOIN orders ON customers.customer_id = orders.customer_id JOIN order_details ON orders.order_id = order_details.order_id GROUP BY customers.customer_id, customers.company_name ORDER BY total_revenue DESC LIMIT 10;"},
    {"id": "three_product_revenue", "question": "Best products by revenue", "sql": "SELECT products.product_id, products.product_name, SUM(order_details.unit_price * order_details.quantity * (1 - order_details.discount)) AS total_revenue FROM products JOIN order_details ON products.product_id = order_details.product_id GROUP BY products.product_id, products.product_name ORDER BY total_revenue DESC LIMIT 10;"},
    {"id": "three_product_order_count", "question": "Best products by order count", "sql": "SELECT products.product_id, products.product_name, COUNT(DISTINCT order_details.order_id) AS order_count FROM products JOIN order_details ON products.product_id = order_details.product_id GROUP BY products.product_id, products.product_name ORDER BY order_count DESC LIMIT 10;"},
    {"id": "three_category_revenue", "question": "Sales by category", "sql": "SELECT categories.category_name, SUM(order_details.unit_price * order_details.quantity * (1 - order_details.discount)) AS total_revenue FROM categories JOIN products ON categories.category_id = products.category_id JOIN order_details ON products.product_id = order_details.product_id GROUP BY categories.category_name ORDER BY total_revenue DESC;"},
    {"id": "agg_order_count", "question": "How many orders are there", "sql": "SELECT COUNT(*) AS order_count FROM orders;"},
    {"id": "agg_avg_freight", "question": "What is the average freight", "sql": "SELECT AVG(orders.freight) AS average_freight FROM orders;"},
    {"id": "agg_inventory", "question": "Total units in stock", "sql": "SELECT SUM(products.units_in_stock) AS total_units_in_stock FROM products;"},
    {"id": "having_customers", "question": "Customers with more than ten orders", "sql": "SELECT customers.customer_id, customers.company_name, COUNT(orders.order_id) AS order_count FROM customers JOIN orders ON customers.customer_id = orders.customer_id GROUP BY customers.customer_id, customers.company_name HAVING COUNT(orders.order_id) > 10 ORDER BY order_count DESC;"},
    {"id": "having_categories", "question": "Categories with revenue over 10000", "sql": "SELECT categories.category_name, SUM(order_details.unit_price * order_details.quantity * (1 - order_details.discount)) AS total_revenue FROM categories JOIN products ON categories.category_id = products.category_id JOIN order_details ON products.product_id = order_details.product_id GROUP BY categories.category_name HAVING SUM(order_details.unit_price * order_details.quantity * (1 - order_details.discount)) > 10000 ORDER BY total_revenue DESC;"},
    {"id": "time_monthly_sales", "question": "Monthly sales revenue", "sql": "SELECT DATE_TRUNC('month', orders.order_date) AS month, SUM(order_details.unit_price * order_details.quantity * (1 - order_details.discount)) AS total_revenue FROM orders JOIN order_details ON orders.order_id = order_details.order_id GROUP BY DATE_TRUNC('month', orders.order_date) ORDER BY month;"},
    {"id": "time_current_30", "question": "Orders in the last 30 days", "sql": "SELECT orders.order_id, orders.customer_id, orders.order_date FROM orders WHERE orders.order_date >= (SELECT MAX(orders.order_date) FROM orders) - INTERVAL '30 days' ORDER BY orders.order_date DESC LIMIT 100;"},
]
